version: '3'

services:
    redis_server:
        build:
            context: ./redis_server
        volumes:
            - ./redis_server/data:/data
    app_server:
        build:
            context: ./app_server
        command: tail -f /dev/null
        volumes:
            - ./app_server/app:/usr/local/app
        links:
            - redis_server
